"""Async Python client for the UniFi Access API."""

__version__ = "0.1.1"
API_REFERENCE_VERSION = "4.0.10"

from aiounifiaccess.client import UniFiAccessClient
from aiounifiaccess.errors import (
    AccessPolicyError,
    APIError,
    APINotSupportedError,
    AuthenticationError,
    CredentialError,
    DeviceBusyError,
    DeviceError,
    DeviceNotFoundError,
    DeviceOfflineError,
    DeviceVersionError,
    HolidayGroupError,
    InvalidParametersError,
    NFCCardBoundError,
    NFCCardInvalidError,
    NFCCardProvisionError,
    PINCodeExistsError,
    RateLimitedError,
    RequestFailedError,
    ResourceConflictError,
    ResourceNotFoundError,
    ServerError,
    UnauthorizedError,
    UniFiAccessError,
    UniFiConnectionError,
)
from aiounifiaccess.events import (
    BaseEvent,
    BaseInfoEvent,
    DoorbellCompletedEvent,
    DoorbellIncomingEvent,
    DoorbellRENEvent,
    DoorPositionEvent,
    DoorUnlockEvent,
    EmergencyStatusEvent,
    RawEvent,
    RemoteUnlockEvent,
    RemoteViewChangeEvent,
    RemoteViewEvent,
    TemporaryUnlockEndEvent,
    TemporaryUnlockStartEvent,
    UnlockScheduleActivateEvent,
    UnlockScheduleDeactivateEvent,
    VisitorStatusChangedEvent,
    verify_webhook_signature,
)
from aiounifiaccess.models import (
    AccessMethodSettings,
    AccessPolicy,
    Door,
    DoorGroup,
    DoorGroupTopology,
    DoorGroupType,
    DoorLockStatus,
    DoorPositionStatus,
    EmergencyStatus,
    HolidayGroup,
    IdentityResource,
    LockRule,
    LockRuleType,
    LogTopic,
    NFCCard,
    NFCCardEnrollmentStatus,
    ResourceType,
    Schedule,
    SystemLogEntry,
    TouchPass,
    User,
    UserGroup,
    UserStatus,
    Visitor,
    VisitorStatus,
    WebhookEndpoint,
)

__all__ = [
    # Client
    "UniFiAccessClient",
    # Version
    "__version__",
    "API_REFERENCE_VERSION",
    # Models
    "AccessMethodSettings",
    "AccessPolicy",
    "Door",
    "DoorGroup",
    "DoorGroupTopology",
    "DoorGroupType",
    "DoorLockStatus",
    "DoorPositionStatus",
    "EmergencyStatus",
    "HolidayGroup",
    "IdentityResource",
    "LockRule",
    "LockRuleType",
    "LogTopic",
    "NFCCard",
    "NFCCardEnrollmentStatus",
    "ResourceType",
    "Schedule",
    "SystemLogEntry",
    "TouchPass",
    "User",
    "UserGroup",
    "UserStatus",
    "Visitor",
    "VisitorStatus",
    "WebhookEndpoint",
    # Events
    "BaseEvent",
    "BaseInfoEvent",
    "DoorbellCompletedEvent",
    "DoorbellIncomingEvent",
    "DoorbellRENEvent",
    "DoorPositionEvent",
    "DoorUnlockEvent",
    "EmergencyStatusEvent",
    "RawEvent",
    "RemoteUnlockEvent",
    "RemoteViewChangeEvent",
    "RemoteViewEvent",
    "TemporaryUnlockEndEvent",
    "TemporaryUnlockStartEvent",
    "UnlockScheduleActivateEvent",
    "UnlockScheduleDeactivateEvent",
    "VisitorStatusChangedEvent",
    "verify_webhook_signature",
    # Errors
    "APIError",
    "APINotSupportedError",
    "AccessPolicyError",
    "AuthenticationError",
    "CredentialError",
    "DeviceBusyError",
    "DeviceError",
    "DeviceNotFoundError",
    "DeviceOfflineError",
    "DeviceVersionError",
    "HolidayGroupError",
    "InvalidParametersError",
    "NFCCardBoundError",
    "NFCCardInvalidError",
    "NFCCardProvisionError",
    "PINCodeExistsError",
    "RateLimitedError",
    "RequestFailedError",
    "ResourceConflictError",
    "ResourceNotFoundError",
    "ServerError",
    "UnauthorizedError",
    "UniFiAccessError",
    "UniFiConnectionError",
]
